apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-app
  namespace: jhipster
  labels:
    team: jhipster
spec:
  selector:
    matchLabels:
      app: product
  endpoints:
    - port: web
      path: /prometheusMetrics
