apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: marvelousanything/invoice
      context: ./invoice
      jib:
        args:
          - "-Djib.httpTimeout=1820000"
          - "-DallowInsecureRegistries=true"
          - "-DsendCredentialsOverHttp=true"
    - image: marvelousanything/notification
      context: ./notification
      jib:
        args:
          - "-Djib.httpTimeout=1820000"
          - "-DallowInsecureRegistries=true"
          - "-DsendCredentialsOverHttp=true"
    - image: marvelousanything/product
      context: ./product
      jib:
        args:
          - "-Djib.httpTimeout=1820000"
          - "-DallowInsecureRegistries=true"
          - "-DsendCredentialsOverHttp=true"
    - image: marvelousanything/store
      context: ./store
      jib:
        args:
          - "-Djib.httpTimeout=1820000"
          - "-DallowInsecureRegistries=true"
          - "-DsendCredentialsOverHttp=true"
deploy:
  kustomize: {}
